import standards from '@nextnode-solutions/standards/oxfmt'
import { defineConfig } from 'oxfmt'

// oxfmt has no `extends`: spread the shared preset and layer repo-local
// ignores on top of it.
export default defineConfig({
	...standards,
	ignorePatterns: [
		...standards.ignorePatterns,
		'node_modules/**',
		'dist/**',
		// GENERATED by scripts/fetch-icons.mjs; re-run the script, don't format it.
		'src/ui/icon-data.ts',
		// GENERATED by test/benchmarks/bench-dashboard.mjs (history.json + dashboard-template.html);
		// re-run the generator, don't format it.
		'test/benchmarks/dashboard.html',
		// Markdown is hand-maintained docs (AGENTS.md, README, skills, prompts)
		// and stays unformatted per the harness policy.
		'**/*.md',
		'.desk/**',
		'.pi/**',
		'.prd/**',
		'prototypes/**',
		'.playwright-mcp/**',
	],
})
