import standards from '@nextnode-solutions/standards/oxlint'
import { defineConfig } from 'oxlint'

export default defineConfig({
	extends: [standards],
	// Setting ignorePatterns replaces oxlint's built-in ignore list, so
	// node_modules/dist are listed explicitly next to Galley's build output,
	// generated sources and runtime artifacts (desk locks, pi shims, scratch).
	ignorePatterns: [
		'node_modules/**',
		'dist/**',
		// GENERATED by scripts/fetch-icons.mjs; re-run the script, don't lint it.
		'src/ui/icon-data.ts',
		'.desk/**',
		'.pi/**',
		'.prd/**',
		'prototypes/**',
		'.playwright-mcp/**',
	],
	overrides: [
		{
			// The pi extension entry point default-exports its register function by
			// design: pi's loader contract, the same class of exception as framework
			// pages in the shared preset.
			files: ['extensions/galley.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
		{
			// `types/standards-oxfmt.d.ts` describes the shared preset's default
			// export; the default is the shape being typed, not an export-style
			// choice this repo makes.
			files: ['types/**/*.d.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
	],
})
