import standards from '@nextnode-solutions/standards/oxlint'
import { defineConfig } from 'oxlint'

// Cross-layer imports are aliased (each sliced layer below declares its upward
// alias bans); these relative variants close the textual bypass so a sliced
// layer cannot reach another layer - or another slice of its own layer - by
// spelling the path relatively. The enumerated climbs (../ through ../../../)
// cover the deepest current frontend nesting; from deeper files a shallower
// climb resolves inside the own slice (where the target never exists), so the
// variants only ever fire on real escapes. Intra-slice imports (./peer,
// ../model) stay relative and remain legal; app/ and worker/ are composition
// roots and import every layer by design.
const relativeLayerEscapes = (...targets: string[]): string[] =>
	targets.flatMap(target => [
		`../${target}`,
		`../${target}/**`,
		`../../${target}/**`,
		`../../../${target}/**`,
	])

export default defineConfig({
	extends: [standards],
	// Setting ignorePatterns replaces oxlint's built-in ignore list, so
	// node_modules/dist are listed explicitly next to Syneva's build output,
	// generated sources and runtime artifacts (desk locks, pi shims, scratch).
	ignorePatterns: [
		'node_modules/**',
		'dist/**',
		// GENERATED by scripts/fetch-icons.mjs; re-run the script, don't lint it.
		'src/frontend/shared/ui/icon-data.ts',
		'.desk/**',
		'.pi/**',
		'.prd/**',
		'prototypes/**',
		'.playwright-mcp/**',
	],
	overrides: [
		{
			// The token pool's pinned-library seam: @pierre/diffs pins a nominal-class
			// WorkerPoolManager (private fields, no structural half) and types helpers against the
			// full shiki v3 barrel (DiffsHighlighter) while syneva builds a lean shiki v4(core)
			// instance; DOM libs also lack DedicatedWorkerGlobalScope so the worker scope needs a
			// narrow view. Every assertion lives next to its seam and is documented there.
			// Token-pool files also log failures (an unhighlighted desk must show WHY, not stay
			// silent), and post worker messages without target-origin (workers post by identity,
			// the rule targets window contexts).
			files: [
				'src/frontend/widgets/diff-view/worker-pool.ts',
				'src/frontend/worker/diff-token-worker.ts',
				'src/frontend/shared/diff-renderer/token-pool/*.ts',
			],
			rules: {
				'nextnode/no-type-assertion': 'off',
				// The type-aware pass sees the same seams as unsafe (the nominal pool cast, the
				// DiffsHighlighter parameter shape, the window-scope view).
				'typescript/no-unsafe-type-assertion': 'off',
				'unicorn/require-post-message-target-origin': 'off',
				'eslint/no-console': 'off',
				// The pool's PoolJob/WindowTask records are one piece of shared mutable state the
				// class owns: settlement paths (window landed, worker crashed, options adopted)
				// mutate the same record through their parameters by design - copying it per call
				// would fork the state the countdown and the gate are read from.
				'eslint/no-param-reassign': 'off',
				// The single-class pool (pool.ts) is deliberate: the v1 book split the same state
				// machine across six modules whose only seams were call boundaries. Keep the file
				// cap from splitting it again.
				'eslint/max-lines': 'off',
			},
		},
		{
			// The hide-reviewed distill pass is a mechanical translation of @pierre's own
			// resolveRegion cursor walk (same counters, same collapsed-context handling, minus
			// dropped rows) - the pinned-library seam's shape, not a reviewable logic tree.
			// Splitting it would scatter one invariant (the lockstep ledger) across closures.
			files: ['src/frontend/shared/diff-renderer/distill.ts'],
			rules: {
				'eslint/max-lines-per-function': 'off',
				'eslint/max-depth': 'off',
			},
		},
		{
			// The long-poll consumes the next queued event. Parallel requests would
			// reorder feedback and detach event ownership from its delivery.
			files: ['src/backend/adapters/inbound/pi/desk-listener.ts'],
			rules: { 'eslint/no-await-in-loop': 'off' },
		},
		{
			// The question pipeline is sequential by design: the single desk correspondent
			// thread answers one event at a time, and answers post to the desk in question
			// order (the same class of exception as the desk-listener long-poll below).
			files: [
				'src/backend/adapters/inbound/pi/pi-attachment.ts',
				'src/backend/adapters/inbound/pi/pi-delivery.ts',
			],
			rules: { 'eslint/no-await-in-loop': 'off' },
		},
		{
			// The integration test polls the desk state until the skipped-owner answer
			// appears: live polling, not parallelizable promise collection.
			files: [
				'src/backend/adapters/inbound/pi/pi-attachment.integration.test.ts',
			],
			rules: { 'eslint/no-await-in-loop': 'off' },
		},
		{
			// Layer boundaries, enforced on the literal relative specifier (every
			// intra-repo import is relative; the depth variants cover src/backend's
			// subtree and the deepest src/frontend folders):
			// - contracts is a neutral dependency sink: no backend, no UI.
			// - domain is pure: no contracts (its shapes are re-declared), no adapter
			//   IO, no UI - and, outside tests, no process/filesystem/network builtins
			//   (node:crypto stays allowed for pure hashing).
			// - the backend never imports the browser world.
			// - the browser never imports the backend.
			files: ['src/contracts/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../backend',
									'../backend/**',
									'../frontend',
									'../frontend/**',
								],
								message:
									'contracts is a neutral dependency sink - it imports no backend/frontend module.',
							},
						],
					},
				],
			},
		},
		{
			// Domain is pure. One rule set (later overrides replace earlier rules for the
			// same files, so the two restrictions live together): no contracts (shared
			// shapes are re-declared in review.ts), no adapter/application imports, no UI
			// - and, outside tests, no process/filesystem/network builtins. node:crypto
			// stays allowed for pure hashing.
			files: ['src/backend/domain/*.ts', 'src/backend/domain/**/*.ts'],
			excludeFiles: ['**/*.test.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../contracts/**',
									'../../contracts/**',
									'../../../contracts/**',
									'../adapters/**',
									'../../adapters/**',
									'../../../adapters/**',
									'../application/**',
									'../../application/**',
									'../../../application/**',
									'../frontend/**',
									'../../frontend/**',
									'../../../frontend/**',
								],
								message:
									'domain is pure - no contracts (shared shapes are re-declared in review.ts), no adapters/application, no UI.',
							},
						],
					},
					{
						patterns: [
							{
								group: ['fs', 'node:fs'],
								message: 'domain is pure - no filesystem.',
							},
							{
								group: ['http', 'node:http'],
								message: 'domain is pure - no HTTP.',
							},
							{
								group: ['child_process', 'node:child_process'],
								message:
									'domain is pure - no process spawning.',
							},
							{
								group: ['net', 'node:net'],
								message: 'domain is pure - no networking.',
							},
							{
								group: ['process', 'node:process'],
								message: 'domain is pure - no process access.',
							},
						],
					},
				],
			},
		},
		{
			// Domain tests may drive real git/fixture IO, so only the module boundary
			// (not the builtin restriction above) applies to them.
			files: [
				'src/backend/domain/*.test.ts',
				'src/backend/domain/**/*.test.ts',
			],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../contracts/**',
									'../../contracts/**',
									'../../../contracts/**',
									'../adapters/**',
									'../../adapters/**',
									'../../../adapters/**',
									'../application/**',
									'../../application/**',
									'../../../application/**',
									'../frontend/**',
									'../../frontend/**',
									'../../../frontend/**',
								],
								message:
									'domain is pure - no contracts (shared shapes are re-declared in review.ts), no adapters/application, no UI.',
							},
						],
					},
				],
			},
		},
		{
			// The backend never imports the browser UI world. Domain files are excluded:
			// their stricter (pure) rule set is defined above and a later override would
			// replace it wholesale.
			files: ['src/backend/**/*.ts'],
			excludeFiles: ['src/backend/domain/**'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../frontend',
									'../frontend/**',
									'../../frontend/**',
									'../../../frontend/**',
									'../../../../frontend/**',
									'../../../../../frontend/**',
									'../../../../../../frontend/**',
								],
								message:
									'the backend never imports the browser UI world.',
							},
						],
					},
				],
			},
		},
		{
			// FSD layer boundaries for the frontend, enforced on the layer aliases (every
			// cross-layer import is an aliased specifier; intra-slice imports stay relative).
			// Each layer below has exactly ONE effective no-restricted-imports declaration
			// (a later override would replace the whole rule for the same files, so everything
			// - the browser-to-backend prohibition, the upward-layer bans, and the same-layer
			// alias bans - is folded into that one declaration; the previous trailing broad
			// frontend override, which silently replaced these rules, is gone):
			// - no frontend file ever imports the backend (contracts is the only sink).
			// - app and the worker are composition roots: no same-layer or upward ban.
			// - sliced layers (entities/features/widgets/pages) also ban their own layer
			//   alias: same-layer slices stay composition-only at their consumers and
			//   intra-slice imports stay relative. The one deliberate exception is the
			//   features layer seam @features/context, through which app composition binds
			//   the narrow feature ports.
			files: ['src/frontend/shared/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../backend/**',
									'../../backend/**',
									'../../../backend/**',
									'../../../../backend/**',
									'../../../../../backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
									'@widgets',
									'@widgets/**',
									'@features',
									'@features/**',
									'@entities',
									'@entities/**',
								],
								message:
									'shared imports nothing above itself - only other shared modules and @contracts.',
							},
							{
								group: [
									'../app',
									'../app/**',
									'../../app/**',
									'../../../app/**',
									'../pages',
									'../pages/**',
									'../../pages/**',
									'../../../pages/**',
									'../widgets',
									'../widgets/**',
									'../../widgets/**',
									'../../../widgets/**',
									'../features',
									'../features/**',
									'../../features/**',
									'../../../features/**',
									'../entities',
									'../entities/**',
									'../../entities/**',
									'../../../entities/**',
									'../worker',
									'../worker/**',
									'../../worker/**',
									'../../../worker/**',
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside shared/.',
							},
						],
					},
				],
			},
		},
		{
			files: ['src/frontend/entities/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../backend/**',
									'../../backend/**',
									'../../../backend/**',
									'../../../../backend/**',
									'../../../../../backend/**',
									'../../../../../../backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
									'@widgets',
									'@widgets/**',
									'@features',
									'@features/**',
								],
								message:
									'entities import shared and entities only - never features/widgets/pages/app.',
							},
							{
								group: ['@entities/**'],
								message:
									'entities never import another entity slice; intra-slice imports are relative.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'pages',
										'widgets',
										'features',
										'shared',
										'worker',
									),
									...relativeLayerEscapes('settings'),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside the entity slice.',
							},
						],
					},
				],
			},
		},
		{
			files: ['src/frontend/features/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../backend/**',
									'../../backend/**',
									'../../../backend/**',
									'../../../../backend/**',
									'../../../../../backend/**',
									'../../../../../../backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
									'@widgets',
									'@widgets/**',
								],
								message:
									'features import entities/shared only - never widgets/pages/app.',
							},
							{
								group: ['@features/**', '!@features/context'],
								message:
									'features never import another feature slice; intra-slice imports are relative. The layer seam @features/context is the one exception.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'pages',
										'widgets',
										'entities',
										'shared',
										'worker',
									),
									...relativeLayerEscapes(
										'decide-change',
										'expand-context',
										'manage-comment',
										'open-editor',
										'send-review',
									),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside the feature slice.',
							},
						],
					},
				],
			},
		},
		{
			files: ['src/frontend/widgets/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../backend/**',
									'../../backend/**',
									'../../../backend/**',
									'../../../../backend/**',
									'../../../../../backend/**',
									'../../../../../../backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: [
									'@app',
									'@app/**',
									'@pages',
									'@pages/**',
								],
								message:
									'widgets import features/entities/shared only - never pages/app.',
							},
							{
								group: ['@widgets/**'],
								message:
									'widgets never import another widget slice; intra-slice imports are relative.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'pages',
										'features',
										'entities',
										'shared',
										'worker',
									),
									...relativeLayerEscapes(
										'chrome',
										'dialogs',
									),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside the widget slice.',
							},
						],
					},
				],
			},
		},
		{
			files: ['src/frontend/pages/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../backend/**',
									'../../backend/**',
									'../../../backend/**',
									'../../../../backend/**',
									'../../../../../backend/**',
									'../../../../../../backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
							{
								group: ['@app', '@app/**'],
								message:
									'pages compose widgets/features/entities/shared - they never import app.',
							},
							{
								group: [
									...relativeLayerEscapes(
										'app',
										'widgets',
										'features',
										'entities',
										'shared',
										'worker',
									),
								],
								message:
									'cross-layer imports use the layer aliases - relative paths must stay inside pages/.',
							},
							{
								group: ['@pages/**'],
								message:
									'pages never import another page slice; intra-slice imports are relative.',
							},
						],
					},
				],
			},
		},
		{
			// app and the worker are composition roots: they may import every layer
			// (app/facade modules even import @app/store by design) - but never the backend.
			files: ['src/frontend/app/**/*.ts', 'src/frontend/worker/**/*.ts'],
			rules: {
				'eslint/no-restricted-imports': [
					'error',
					{
						patterns: [
							{
								group: [
									'../backend/**',
									'../../backend/**',
									'../../../backend/**',
									'../../../../backend/**',
									'../../../../../backend/**',
									'../../../../../../backend/**',
								],
								message:
									'the browser imports contracts only - never the backend.',
							},
						],
					},
				],
			},
		},

		{
			// tsgolint (the type-aware backend) cannot resolve the frontend layer aliases
			// (@app/@pages/... - its module resolution ignores tsconfig paths), so its view
			// of every aliased import is an error type and the rules below fire unsoundly
			// on frontend files (they pass whenever the types resolve - see HEAD and the
			// tsc gates). The type gate for the frontend is tsconfig.ui.json via pnpm
			// check; type-aware linting stays fully active for the backend.
			files: ['src/frontend/**/*.ts', 'src/frontend/**/*.tsx'],
			rules: {
				'typescript/no-redundant-type-constituents': 'off',
				'typescript/prefer-nullish-coalescing': 'off',
				'typescript/no-unnecessary-condition': 'off',
				'typescript/no-unnecessary-type-assertion': 'off',
				'typescript/require-array-sort-compare': 'off',
			},
		},
		{
			// Composition modules are allowed many dependencies by design: app/main.ts wires
			// every slice into the single facade, pages/desk/render.ts is the one render
			// funnel, and widgets/diff-view/diff-instance.ts orchestrates the imperative
			// diff island. Splitting them would scatter composition, not reduce coupling.
			files: [
				'src/frontend/app/main.tsx',
				'src/frontend/pages/desk/render.ts',
				'src/frontend/widgets/diff-view/diff-instance.ts',
			],
			rules: { 'import/max-dependencies': 'off' },
		},
		{
			// The reactive store kernel wraps unknowns by design - the Proxy handlers ARE the
			// wrap/unwrap seam, and the settings descriptor table narrows string options back
			// to their Settings field unions at the single write boundary. The assertions are
			// the seam itself.
			files: [
				'src/frontend/shared/lib/reactive.ts',
				'src/frontend/widgets/chrome/react/settings-descriptors.ts',
			],
			rules: {
				'nextnode/no-type-assertion': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
				// The descriptor table's keys are the domain; the generic just carries the
				// write boundary - the type-aware pass reads it as single-use.
				'typescript/no-unnecessary-type-parameters': 'off',
			},
		},
		{
			// The React chrome is a view over the mutable reactive store: the store IS the
			// state channel (an external observable, subscribed via useSyncExternalStore),
			// so handler-side writes (S.field = …, settings.x = …) are the designed mutation
			// path, not a render-phase mutation. The rule cannot see that boundary; disable it
			// for the chrome views only. Actions with logic still live in the facade modules.
			// The effects sync EXTERNAL systems the store does not own: the browser tab
			// title, the body layout classes, the rAF count-up animation - none of them
			// are render-time derivations.
			files: [
				'src/frontend/widgets/chrome/react/**',
				'src/frontend/app/react/app.tsx',
			],
			rules: {
				'react/immutability': 'off',
				// A view composition keeps its row/action fragments in one file (each still
				// within the size and complexity caps); scattering fragments into files-per
				// -component would separate the pieces that only make sense together.
				'react/no-multi-comp': 'off',
				'nextnode/no-use-effect': 'off',
			},
		},
		{
			// The bench fixtures encode file counts and per-file sizes by design (an 8k-line
			// giant, a 2.4MB oversized file) and the browser bench reports with console.log
			// like perf-smoke does. The shared preset's readability rules (magic numbers,
			// function length, await depth) fight the fixture specs' shape, not a reviewable
			// logic path - drop them for the bench scripts only.
			files: [
				'test/benchmarks/bench-fixtures.mjs',
				'test/benchmarks/browser-bench.mjs',
				'test/benchmarks/perf-smoke.mjs',
			],
			rules: {
				'eslint/no-magic-numbers': 'off',
				'eslint/no-console': 'off',
				'eslint/max-lines': 'off',
				'eslint/max-lines-per-function': 'off',
				'eslint/max-depth': 'off',
				'nextnode/no-nullish-ternary-return': 'off',
				// The bench instruments (a page-side __bench projector, fetch/Worker hooks,
				// measured-and-sequenced key presses) are inherently serialized and
				// underscore-named on purpose: the page API surface they reach into is
				// syneva's own store singleton. Sequenced awaits (cold-open pipeline,
				// latency probes, churn loops) measure sequences - parallelizing them would
				// change the thing being measured.
				'eslint/no-underscore-dangle': 'off',
				'eslint/no-await-in-loop': 'off',
			},
		},
		{
			// The harness extension entry point default-exports its register function by
			// design: pi's loader contract, the same class of exception as framework
			// pages in the shared preset.
			files: ['extension/syneva.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
		{
			// `types/standards-oxfmt.d.ts` describes the shared preset's default
			// export; the default is the shape being typed, not an export-style
			// choice this repo makes.
			files: ['types/**/*.d.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
	],
})
